"""add deleted_at column to all tables

Revision ID: df5241ade4c4
Revises: 78a92669ff75
Create Date: 2026-03-16 06:30:31.394035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df5241ade4c4'
down_revision: Union[str, Sequence[str], None] = '78a92669ff75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('audit_logs', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('categories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('notifications', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('settings', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('task_shares', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('task_shares', 'deleted_at')
    op.drop_column('settings', 'deleted_at')
    op.drop_column('notifications', 'deleted_at')
    op.drop_column('categories', 'deleted_at')
    op.drop_column('audit_logs', 'deleted_at')
    op.drop_column('attachments', 'deleted_at')
    # ### end Alembic commands ###
