"""fix user notification columns

Revision ID: e1f2g3h4i5j6
Revises: df5241ade4c4
Create Date: 2026-03-16 07:42:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f2g3h4i5j6'
down_revision: Union[str, Sequence[str], None] = 'df5241ade4c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('push_notifications', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('task_updates', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('system_alerts', sa.Boolean(), nullable=True, server_default=sa.text('true')))
    op.add_column('users', sa.Column('profile_image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'system_alerts')
    op.drop_column('users', 'task_updates')
    op.drop_column('users', 'push_notifications')
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
